language: java
jdk: oraclejdk8

#Define the services to use
services:
  - docker
before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

# Environment variables are strings (double quotes)
# Example:
# - secure: "DpR1th9rZvLMX0......"
env:
  global:
    - secure: "3dbfd3a1b82abf56a33f2190b3d79c202f4f504b"

# The pipe (|) is useful to create multiline scripts
script:
  - |
    mvn clean install sonar:sonar \
    mvn sonar:sonar \
    -Dsonar.projectKey=fdisson_sample-application-students \
    -Dsonar.organization=fdisson-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=3dbfd3a1b82abf56a33f2190b3d79c202f4f504b